---
name: Build

on:
  push:
  schedule:  # To keep the artifacts around
    - cron: '23 5 13 */2 *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: liff
          authToken: '${{ secrets.cachix_auth_token }}'
          signingKey: '${{ secrets.cachix_signing_key }}'

      - run: nix flake update

      - run: nix -L build

      - name: Commit changes, if any
        uses: EndBug/add-and-commit@v9
        with:
          add: 'flake.lock'
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Update flake inputs'
